FROM eclipse-temurin:17-jre

WORKDIR /app

COPY target/ms3-movements-0.0.1-SNAPSHOT.jar app.jar

ENV MOVEMENTS_DB_HOST=movements-mongo
ENV MOVEMENTS_DB_PORT=27017
ENV MOVEMENTS_DB_NAME=movements_db

EXPOSE 8002

ENTRYPOINT ["java", "-jar", "app.jar"]